
L = 2*pi;
T = 6;
f = @(x,t) 2*exp(-t/2)*sin(x/2);
u0 = @(x) sin(x/2);
v0 = @(x) -sin(x/2);
gleft = @(t) sin(pi/6*t);
gright = @(t) sin(pi/12*t);
a = 1/(4*pi^2);
nx = 31;
nt = 41;
hx = L/(nx - 1);
ht = T/(nt - 1);
x = 0:hx:L;
t = 0:ht:T;
u = wave1(f, u0, v0, gleft, gright, a, nx, nt, L, T);
figure(1);
surf(x, t, u');
axis([0 7 0 6 0 12]);
set(gca, 'xtick', 0:7);
set(gca, 'ytick', 0:6);
set(gca, 'ztick',0:2:12);
xlabel('x');
ylabel('t');
zlabel('u');
title('Assignment 12, Figure 1');

figure(2);
nx = 46;
nt = 61;
hx = L/(nx - 1);
ht = T/(nt - 1);
x = 0:hx:L;
t = 0:ht:T;
u = wave1(f, u0, v0, gleft, gright, a, nx, nt, L, T);
surf(x, t, u');
axis([0 7 0 6 0 12]);
set(gca, 'xtick', 0:7);
set(gca, 'ytick', 0:6);
set(gca, 'ztick',0:2:12);
xlabel('x');
ylabel('t');
zlabel('u');
title('Assignment 12, Figure 2');